### ISSUE TITLE
Webhook URL is exposed, leading to possible webhook abuse

### ISSUE THREAD

**Issue by tulpenkiste** [Level-Share-Square/SuperMario127#14]
https://github.com/Level-Share-Square/SuperMario127/blob/27ded630485da497aca0ef3581ae9059090203eb/.github/workflows/notif.yml#L15

**Comment by tulpenkiste** [comment]
https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions

**Comment by axelorca** [comment]
Webhook link has been reset and hidden
